baseURL = "http://localhost:1313/"
title = "Rithmory"
theme = "blowfish"
enableRobotsTXT = true
summaryLength = 30
enableEmoji = true
defaultContentLanguage = "en"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[pagination]
pagerSize = 15
